# Generated by Django 2.2.6 on 2019-10-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignatura', '0002_remove_asignatura_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
