# Generated by Django 2.2.6 on 2019-10-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0002_remove_docente_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='identificacion',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
